apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emqx.fullname" . }}-timescale
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  "emqx_backend_timescale.conf": |
    {{ .Values.emqxTimescaleConf }}